version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: launchdude
    main: ./
    binary: launchdude
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/evnoj/launchdude/cmd.version={{.Version}}

archives:
  - id: launchdude
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
